config/routes.rb
Rails.application.routes.draw do
  root to: 'stations#index'
  get '/stations', to: 'stations#index'
  get '/stations/:id', to: 'stations#show'
  
  resources :trips, except: [:destroy]
  resources :bikes, only: [:index, :show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :station
  belongs_to :bike_status
  has_many :trips
end

app/models/bike_status.rb
class BikeStatus < ApplicationRecord
  has_many :bikes

  validates :description, presence: true, uniqueness: true
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :bikes

  validates :capacity, presence: true
  validates :neighborhood, presence: true, uniqueness: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :start_time, presence: true
  validates :bike_id, presence: true
  validates :origin_station_id, presence: true
  validates :user_id, presence: true

  validate :disallow_park_in_origin

  private
  def disallow_park_in_origin
    if (origin_station_id == destiny_station_id)
      errors.add(:origin_station_id, 'Your trip has to end in a different station')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips

    validates :document_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    before_action :set_bike, only: [:show, :edit, :update]
  
    def index
      @bikes = Bike.all
    end
  
    def show
      @bike = Bike.find(params[:id])
      
      @available_statuses = []
      current_bike_status = @bike.bike_status.description
      if current_bike_status == 'In station'
        available_status_objects = BikeStatus.where(description: 'In use').or(BikeStatus.where(description: 'Needs repair'))
      else 
        available_status_objects = BikeStatus.where(description: 'In station')
      end
  
      available_status_objects.each do |status|
        @available_statuses << [status.id, status.description]
      end
    end
  
    def edit
    end
  
    def update
      @bike.update(bike_params)
      redirect_to bike_path(@bike)
    end
  
    private
    def set_bike
      @bike = Bike.find(params[:id])
    end
  
    def bike_params
      params.require(:bike).permit(:station_id, :bike_status_id)
    end
  end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
    def index
      @stations = Station.all
    end
  
    def show
      @station = Station.find(params[:id])
    end
  end

app/controllers/trips_controller.rb
require 'httparty'

class TripsController < ApplicationController
    include HTTParty
    before_action :set_trip, only: [:show, :edit, :update]
  
    def index
      @trips = Trip.all
    end
  
    def show
      @origin_station = Station.where(id: @trip.origin_station_id)
      @user = User.find(@trip.user_id)
  
      @destiny_stations = [] 
      destiny_stations_objects = Station.all - @origin_station
  
      destiny_stations_objects.each do |object|
        @destiny_stations << [object.id, object.neighborhood]
      end
    end
  
    def new
      @trip = Trip.new
      @users = []
  
      User.all.each do |user|
        @users << [user.id, user.name]
      end
    end
  
    def create
      @bike = Bike.find(params['trip']['bike_id'].to_i)
      if @bike.bike_status.description == 'In station'
        @trip = Trip.new(trip_params)
        @trip.start_time = Time.new
      else
        render :new
      end
      if @trip.save
        bike_status = BikeStatus.where(description: 'In use').first
        @bike.bike_status_id = bike_status.id
        @bike.save
        redirect_to trip_path(@trip), notice: 'Bike alugada!'
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      station = Station.find(trip_params['destiny_station_id'].to_i)
      all_bikes_in_station = StationPresenter.new(station).all_bikes.count
      
      if (all_bikes_in_station + 1) > station.capacity
        flash[:notice] = 'Finalizar a viagem em outra estação, pois esta encontra-se cheia.'
        redirect_to trip_path(@trip)
      else
        if @trip.update(trip_params)
          @trip.end_time = Time.new
          @trip.value = calculate_trip_value(@trip)
          @trip.save

          bike_status = BikeStatus.where(description: 'In station').first
          bike = Bike.find(@trip.bike_id)
          bike.bike_status_id = bike_status.id
          bike.station_id = @trip.destiny_station_id
          bike.save 
          
          send_api_trip_notification(@trip)
          
          if @response.code == 201
              flash[:notice] = 'Viagem finalizada!'
              redirect_to trip_path(@trip)
          else
              flash[:notice] = @response.message
              redirect_to trip_path(@trip)
          end
        else
          flash[:trip_errors] = @trip.errors.full_messages
          redirect_to trip_path(@trip)
        end
      end
    end
  
    private
    def set_trip
      @trip = Trip.find(params[:id])
    end
  
    def trip_params
      params.require(:trip).permit(:origin_station_id, :destiny_station_id, :travelled_distance_meter, :bike_id, :user_id)
    end

    def send_api_trip_notification(trip)
        access = ENV["ACCESS_API_KEY"]
        @response = HTTParty.post('https://springfield-biketipovc.herokuapp.com/trips', 
        :body => {  user_id: trip.user_id,
                    bike_id: trip.bike_id,
                    started_at: "#{trip.start_time}",
                    finished_at: "#{trip.end_time}",
                    travelled_distance: "#{trip.travelled_distance_meter.to_f}",
                    origin: { station_id: trip.origin_station_id},
                    origin: { destination_id: trip.destiny_station_id }
                }.to_json,
        :headers => { 'Content-Type' => 'application/json', 'Authorization' => "Token #{access}" })
        return @response
    end

    def calculate_trip_value(trip)
      time_delta = (trip.end_time - trip.start_time)
      to_minutes = (time_delta / 60).to_i

      if to_minutes < 61
        value = 0
      else
        exceeding_minutes = to_minutes - 60
        if to_minutes % 5 == 0  
          value = 10 + (((exceeding_minutes)/5)*0.2).round(2)
        else
          value = 10 + (((exceeding_minutes/5) + 1)*0.2).round(2)
        end
      end
      return value
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/bikes/_edit.html.erb
<%= simple_form_for @bike do |f| %>
    <%= f.input :bike_status_id, label: 'New bike status ', collection: @available_statuses, label_method: :second, value_method: :first%>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/bikes/index.html.erb
<h1>Bikes</h1>
<p><%= link_to 'Estações', '/stations' %> | <%= link_to 'Viagens', '/trips' %></p>
<div>
    <ul>
        <% @bikes.each do |bike| %>
            <li>
                <% presenter = BikePresenter.new(bike)%>
                <p>
                # <%= bike.id %>
                <%= link_to "Bairro: #{presenter.current_station.neighborhood}", "/stations/#{presenter.current_station.id}" %> |
                Status: <%= presenter.current_status %>
                <%= link_to "Mudar status", bike_path(bike) %>
            </li>
        <% end %>
    </ul>
</div>

app/views/bikes/show.html.erb
<h1>Bike #<%= @bike.id%></h1>
<%= link_to "Bikes", '/bikes'%>
<div>
    <% presenter = BikePresenter.new(@bike)%>
    <p>
        Bairro: <%= presenter.current_station.neighborhood %> |
        Status: <%= presenter.current_status %>
    </p>
    <%= render 'edit' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeStationManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stations/index.html.erb
<h1>Estações</h1>
<p><%= link_to 'Viagens', '/trips' %> | <%= link_to 'Bikes', '/bikes' %></p>
<div>
    <ul>
        <% @stations.each do |station| %>
            <li>
                <% presenter = StationPresenter.new(station)%>
                <p>
                <%= link_to "Bairro: #{station.neighborhood}", "/stations/#{station.id}" %> |
                Bicicletas disponíveis: <%= presenter.available_bikes_in_station.count %> |
                Bicicletas que precisam de reparos: <%= presenter.need_to_be_repaired.count %> |
                Vagas disponíveis: <%= presenter.spots_available %> |
                Capacidade: <%= station.capacity %>
                <% if presenter.available_bikes_in_station.count > 0 %>
                    <%= link_to "Alugar uma bike", new_trip_path(station) %>
                <% end %>
            </li>
        <% end %>
    </ul>
</div>

app/views/stations/show.html.erb
<h1>Estação <%= @station.neighborhood%></h1>
<div>
    <% presenter = StationPresenter.new(@station)%>
    <p>
        Bairro: <%= @station.neighborhood %> |
        Bicicletas disponíveis: <%= presenter.available_bikes_in_station.count %> |
        Vagas disponíveis: <%= presenter.spots_available %> |
        Capacidade: <%= @station.capacity %>
    </p>
    <p><%= link_to 'Voltar', '/'%></p>
</div>

app/views/trips/_edit.html.erb
<%= simple_form_for @trip do |f| %>
    <%= f.input :destiny_station_id, collection: @destiny_stations, label_method: :second, value_method: :first%>
    <%= f.input :travelled_distance_meter %>
    <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/trips/end_trip.html.erb
<h1>Trips#end_trip</h1>
<p>Find me in app/views/trips/end_trip.html.erb</p>

app/views/trips/index.html.erb
<h1>Viagens</h1>
<p><%= link_to 'Estações', '/stations' %> | <%= link_to 'Bikes', '/bikes' %></p>
<div>
    <ul>
        <% @trips.each do |trip| %>
            <li>
                <p> 
                    <%= link_to "Viagem: #{trip.id}", trip_path(trip) %> | 
                    Usuário: <%= trip.user.name %> | 
                    Bike: <%= trip.bike_id%>
                </p>
                <p>
                    Origem: <%= Station.where(id: trip.origin_station_id).first.neighborhood%> | 
                    Iniciada em: <%= trip.start_time.strftime("%d/%m/%Y às %H:%M")%> 
                </p> 
                    <% if trip.destiny_station_id == nil %>
                        <%= link_to 'Finalizar esta viagem', "trips/#{trip.id}" %>
                    <% else %>
                    <p>    
                        Bairro de destino: <%= Station.where(id: trip.destiny_station_id).first.neighborhood %> | 
                        Finalizada em: <%= trip.end_time.strftime("%d/%m/%Y às %H:%M") %>
                    </p> 
                    <p>
                        Distância (m): <%= trip.travelled_distance_meter%> | Valor da viagem: R$ <%= trip.value %>
                    </p>
                    <% end %>
                </p>
            </li>
        <% end %>
    </ul>
</div>

app/views/trips/new.html.erb
<h1>Alugue uma bike</h1>
<div class="form col-xs-6 col-xs-offset-3">
    <% station = Station.find(params['format'].to_i)%>
    <% presenter = StationPresenter.new(station)%>
    <p>Estação <%= station.neighborhood %></p>
    <%= simple_form_for @trip do |f| %>
        <%= f.input :bike_id, collection: presenter.available_bikes_in_station_by_id %>
        <%= f.input :user_id, collection: @users, label_method: :second, value_method: :first %>
        <%= f.input :origin_station_id, as: :hidden, :input_html => { :value => station.id }%>
        <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
</div>

app/views/trips/show.html.erb
<p class="flash-notice"><%= flash[:notice] %></p>
<h1>Viagem iniciada em <%= @trip.start_time.strftime("%d/%m/%Y às %H:%M") %></h1>
<p><%= link_to 'Viagens', '/trips'%> | <%= link_to 'Estações', '/stations'%> </p>
<div>
    <p>
        Bairro de origem: <%= @origin_station.first.neighborhood %> |
        Usuário: <%= @user.name %>
    </p>
    <% if @trip.destiny_station_id == nil %>
        <p>Finalizar esta viagem</p>
        <%= render 'edit', trip: @trip %>
    <% else %>
        <p>
            Bairro de destino: <%= Station.where(id: @trip.destiny_station_id).first.neighborhood %> | 
            Finalizada em: <%= @trip.end_time.strftime("%d/%m/%Y às %H:%M") %> | 
            Valor da viagem: R$ <%= @trip.value %>
        </p>
    <% end %>
</div>